# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget borders active_color=0xffffff inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
# CONTENT DELETED

[mode.main.binding]
ctrl-enter = "mode activate"

[mode.activate.binding]
ctrl-shift-t = ['''exec-and-forget kitten @ launch --type os-window''', 'mode main']

ctrl-a = ['focus left', 'mode main']
ctrl-s = ['focus down', 'mode main']
ctrl-w = ['focus up', 'mode main']
ctrl-d = ['focus right', 'mode main']

ctrl-shift-a = ['move left', 'mode main']
ctrl-shift-s = ['move down', 'mode main']
ctrl-shift-w = ['move up', 'mode main']
ctrl-shift-d = ['move right', 'mode main']

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
ctrl-h = ['split horizontal', 'mode main']
ctrl-v = ['split vertical', 'mode main']

ctrl-g = ['fullscreen', 'mode main']

ctrl-r = ['layout v_accordion', 'mode main'] # 'layout stacking' in i3
ctrl-t = ['layout h_accordion', 'mode main'] # 'layout tabbed' in i3
ctrl-e= ['layout tiles horizontal vertical', 'mode main'] # 'layout toggle split' in i3

ctrl-f = ['layout floating tiling', 'mode main'] # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#ctrl-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# ctrl-a = 'focus parent'

ctrl-1 = ['workspace 1', 'mode main']
ctrl-2 = ['workspace 2', 'mode main']
ctrl-3 = ['workspace 3', 'mode main']
ctrl-4 = ['workspace 4', 'mode main']
ctrl-5 = ['workspace 5', 'mode main']
ctrl-6 = ['workspace 6', 'mode main']
ctrl-7 = ['workspace 7', 'mode main']
ctrl-8 = ['workspace 8', 'mode main']
ctrl-9 = ['workspace 9', 'mode main']
ctrl-0 = ['workspace 10', 'mode main']

ctrl-shift-1 = ['move-node-to-workspace 1', 'mode main']
ctrl-shift-2 = ['move-node-to-workspace 2', 'mode main']
ctrl-shift-3 = ['move-node-to-workspace 3', 'mode main']
ctrl-shift-4 = ['move-node-to-workspace 4', 'mode main']
ctrl-shift-5 = ['move-node-to-workspace 5', 'mode main']
ctrl-shift-6 = ['move-node-to-workspace 6', 'mode main']
ctrl-shift-7 = ['move-node-to-workspace 7', 'mode main']
ctrl-shift-8 = ['move-node-to-workspace 8', 'mode main']
ctrl-shift-9 = ['move-node-to-workspace 9', 'mode main']
ctrl-shift-0 = ['move-node-to-workspace 10', 'mode main']

# ctrl-r = 'mode resize'

# [mode.resize.binding]
# left = 'resize width -50'
# up = 'resize height +50'
# down = 'resize height -50'
# right = 'resize width +50'
# enter = 'mode main'
# esc = 'mode main'
