# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  config,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
    ./custom.nix
    ../garnix.nix
  ];

  users.users.jw910731 = {
    uid = 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/jw910731";
    homeMode = "700";
    useDefaultShell = true;
    shell = pkgs.zsh;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Taipei";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
            -----BEGIN CERTIFICATE-----
      MIIDkjCCAnqgAwIBAgIQOnWpcP0kDUDFYrXi0eG73DANBgkqhkiG9w0BAQsFADBL
      MQswCQYDVQQGEwJDSDESMBAGA1UEChMJUHJvdG9uIEFHMRQwEgYDVQQLEwtQcm90
      b24gTWFpbDESMBAGA1UEAxMJMTI3LjAuMC4xMB4XDTIzMDgyNDA5MzY0NVoXDTQz
      MDgxOTA5MzY0NVowSzELMAkGA1UEBhMCQ0gxEjAQBgNVBAoTCVByb3RvbiBBRzEU
      MBIGA1UECxMLUHJvdG9uIE1haWwxEjAQBgNVBAMTCTEyNy4wLjAuMTCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMHOz7hKsWnK1mlE6qbxRz11otlifkfK
      Tq7lMNdL+bJ3PrJvrE9hUQZYL3LG5/bH3C7gAe8xe+mmwHxogxRfCnAUmrmNcTRy
      4DR0U3h3qgb0C8BDTQ1JiVXM2Uz4heqhy/1f+VG272go/dk31/Onem6n1AKN1rKo
      cX+KIzb2TP67OrDe4ePasW73g3LiUDfzP/zMcNgDXgeNPe+ILIyPw35P3hUBv4A6
      t170ZSReX/r60LQCLeCEUUds6uJZJoV8wxE3Ub/0OCjgqw5RqWCoFMUlBy/1N1c2
      3pyhlLCY0ZA5YBPpPMEKLxpJvBmHX7DlaNF6dEtZAqEt6oFPlzgAV7sCAwEAAaNy
      MHAwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
      AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTJLIKVo19EoUwnIjsztyctaqBC
      3DAPBgNVHREECDAGhwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQA865+53GSrcUxE
      plI9l849nn4SmjT/zpc+g8+Av9TyuO1W4QtfVz1TL5NSmaZv5GMsBpnuW6KswGtM
      Mi7ukQz5xQTwf1jm+uIQ39UEwQhJEeyXYH9BcFFXqa52LFzZW8ZonWpcilOmES81
      ZFm9v/jifQFFYWcVHhTaftTkWbd86Eklt0S+9a5Kf+VupqIAk61bu3gii2iNX0p/
      gRM9poiqBK/un33A4M001eRkWX4CfaIRrCmeO02wPjuqSIE8KINLCM3EdtCnGSep
      zI4rdQg3JwPXx+uVDsELwnb7uwfowXQlAzXG64j3ucfRDcajLDJOyE4P2PzVs0PL
      IT8XJDLl
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDnjCCAoagAwIBAgIJAPSVc/h8qyC3MA0GCSqGSIb3DQEBCwUAMDkxCzAJBgNV
      BAYTAlRXMRQwEgYDVQQKDAtDSFQgU21hcnRJRDEUMBIGA1UEAwwLQ0hUIFNtYXJ0
      SUQwHhcNMjAwNTE4MDY0MTQwWhcNNDAwNTE4MDY0MTQwWjA5MQswCQYDVQQGEwJU
      VzEUMBIGA1UECgwLQ0hUIFNtYXJ0SUQxFDASBgNVBAMMC0NIVCBTbWFydElEMIIB
      IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnaSpEkGMi4Tg4r7tWgTqf0jg
      1e8y+X4Y8lwkEsaX/kXrxxaNFdvG+ZQE2DZFtpnUSVWnAMPmLo8/A9+Nue8J+KPE
      rnqm1rjMjRIDEpeJIb81007CKdvTVV5ARR5DGIXpYAKw91yJ/akzBjDjRf303BW2
      S8E+3zbKji4OvCxl8fjYZ/yBbmX9yDKO6E95pYvZd/lqhrCXZLJorf4h4OCuu+Kt
      gkGheTk8oUFO/rw/9pQccGn9ruR+NbZIqevlR7iJZke6ul5+czrWTR3Xcf2Wqkh6
      ItGCi7dBurJ4EuI/1c1ZOhF7iFP1PAitBOQFEUsUTL/s7X2Gi6Qoez6x7DbD1QID
      AQABo4GoMIGlMB0GA1UdDgQWBBTRpkzyNgWGBmY1KGMwBrvxr2E5fDBpBgNVHSME
      YjBggBTRpkzyNgWGBmY1KGMwBrvxr2E5fKE9pDswOTELMAkGA1UEBhMCVFcxFDAS
      BgNVBAoMC0NIVCBTbWFydElEMRQwEgYDVQQDDAtDSFQgU21hcnRJRIIJAPSVc/h8
      qyC3MAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IB
      AQAQXftivaoO60Pj5noeXueTSsHJ4WZWHVIBFFzP3fYczp8Uc3txiUR8fUIJpdA/
      0HE63f2q7FD/a3O/agtFCKy/CYp6bIKWR50btjP027w0lbf+0OWkT+C5hS57e7Km
      GmqYb1/m3yKWZgmzaQeyzGUJMt+/FspFM1yUjdq9QyocIv+xtybovTaXa7TaOpal
      VbsBGA5Gv2Nxg9x1SwFSWKoKb4Knw0ybGPLenfBP/S6AID9JaqoSCMbQtLbXS5Kd
      xmNhpHL7LJUN7UuPfxGa7D8I6nY7iBtuz4+MBUScrKkOohmFMWqfG+eKykk8uDs/
      vm7Jzg7sSJk2MG5+8vyPdKq8
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIC6zCCAkygAwIBAgIUI7b68p0pPrCBoW4ptlyvVcPItscwCgYIKoZIzj0EAwQw
      gY0xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
      YW4gRnJhbmNpc2NvMRgwFgYDVQQKEw9DbG91ZGZsYXJlLCBJbmMxNzA1BgNVBAMT
      LkNsb3VkZmxhcmUgZm9yIFRlYW1zIEVDQyBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkw
      HhcNMjAwMjA0MTYwNTAwWhcNMjUwMjAyMTYwNTAwWjCBjTELMAkGA1UEBhMCVVMx
      EzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xGDAW
      BgNVBAoTD0Nsb3VkZmxhcmUsIEluYzE3MDUGA1UEAxMuQ2xvdWRmbGFyZSBmb3Ig
      VGVhbXMgRUNDIENlcnRpZmljYXRlIEF1dGhvcml0eTCBmzAQBgcqhkjOPQIBBgUr
      gQQAIwOBhgAEAVdXsX8tpA9NAQeEQalvUIcVaFNDvGsR69ysZxOraRWNGHLfq1mi
      P6o3wtmtx/C2OXG01Cw7UFJbKl5MEDxnT2KoAdFSynSJOF2NDoe5LoZHbUW+yR3X
      FDl+MF6JzZ590VLGo6dPBf06UsXbH7PvHH2XKtFt8bBXVNMa5a21RdmpD0Pho0Uw
      QzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQU
      YBcQng1AEMMNteuRDAMG0/vgFe0wCgYIKoZIzj0EAwQDgYwAMIGIAkIBQU5OTA2h
      YqmFk8paan5ezHVLcmcucsfYw4L/wmeEjCkczRmCVNm6L86LjhWU0v0wER0e+lHO
      3efvjbsu8gIGSagCQgEBnyYMP9gwg8l96QnQ1khFA1ljFlnqc2XgJHDSaAJC0gdz
      +NV3JMeWaD2Rb32jc9r6/a7xY0u0ByqxBQ1OQ0dt7A==
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIFCDCCA3CgAwIBAgIRAKB6P2fZhUUpcu9uduZClPMwDQYJKoZIhvcNAQELBQAw
      gZsxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTE4MDYGA1UECwwvanc5
      MTA3MzFAanc5MTA3MzEtTWFjQm9vay1BaXIubG9jYWwgKOWQs+aWh+WFgykxPzA9
      BgNVBAMMNm1rY2VydCBqdzkxMDczMUBqdzkxMDczMS1NYWNCb29rLUFpci5sb2Nh
      bCAo5ZCz5paH5YWDKTAeFw0yNDAzMzAyMDE1MjhaFw0zNDAzMzAyMDE1MjhaMIGb
      MR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExODA2BgNVBAsML2p3OTEw
      NzMxQGp3OTEwNzMxLU1hY0Jvb2stQWlyLmxvY2FsICjlkLPmloflhYMpMT8wPQYD
      VQQDDDZta2NlcnQganc5MTA3MzFAanc5MTA3MzEtTWFjQm9vay1BaXIubG9jYWwg
      KOWQs+aWh+WFgykwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCXjiTH
      MqQ5OWwB2pxt2sYlQ0ajfnfRRDzQ9+M/k0t8lEzsoT64sF319P0iXUG1nsE8VRoa
      CS2NQvM7jO31F2Z00qZ/SzZeWzHLg1tG1h3L59Mktog9ZTshWFZS6odCYxMGdbC/
      aPTUcc7ijZwSpJPyCxSAhwJYI+oRMM4ke0NfXnHB1IOWHMZ7t6WzXIjE/CE+xaqX
      yn1UX+0heqJiwo6xso4NuTGV8kyZTSpltj5HWvXVnmMyprGJEqYdpsBDM1biUSgL
      ACGuiXuDqh0xqfYTBBRtFIyPVbKBexCLTngKf0djsZYEAuAjMzPAy+l4mY9KcbPR
      WRaYGHcuAm0LkdMaLlmBnJXdOUGDKq4z8UzlMpul9EaYZbKt18/4P3gq+TnpeUxp
      03ixTBy9dyqUoEiFEmcnRFDVWdshyTKCecOUXUePlLRsdMb/rv2fyY67iaQ+cDf5
      jj9bfG0IHEi2X4m8VQ0QC9Z+ESyvl5iQ4IFPrLrH+OGMvta8F3LXfpKxawcCAwEA
      AaNFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0O
      BBYEFMtnUn/3Y/PoOThuCXzVFDQF3/18MA0GCSqGSIb3DQEBCwUAA4IBgQAKOVVy
      WdI4GKuaQJWtTGkUsjIE8ZEoB+gm2cHSqJlakWEgd1NZv9RI+PQmdMis8yHV4Dja
      m1+7X3bXydV//SWYOGdkMq8C4RCjCUNorBK8VcLZbuP4SS0ZKB+OVQU//r74Pjfl
      vJUqI6wgG5tC3Jj9VRbzX3WY6JhCnVAgz1IZMBPxTPiyNBWQUIqAGWaWUVZ8bctt
      9kSpRC8SsKsHeGkNQg/5iD1jfW3pQpToxDiUHKTT5oWhRAcPwxkKnRfytF81G42k
      ghtKi1fxhd4ZLCCzTIl+hKQLjT9cPZY6F6ogK+zf4LTuVEf9F2WJFKCVHD650yQ6
      Pjv90TlzEvmzNFM1ma0iI6xp0O0NlUeS4PafzJcA+RYD6g6jAnY2v0pqPPmsLm6y
      J4Pkj3HFAeyDC/DE3rTHn5NcVW8R1qgwujJl8hkAPkDj8egkz7sIfS29sqITmlnM
      IxbLPjeH7VxfcfAG2kRFfYX/2zCoRZ+f7g+fuLl0RVUx3e5Fe5mcc0Pkzus=
      -----END CERTIFICATE-----

    ''
  ];

  system.stateVersion = "24.11"; # Did you read the comment?
}
